site_name: 'ClearCare HIPAA Self-Assessment'
site_description: 'HIPAA Self-Assessment for ClearCare'
site_url: 'https://security.clearcareonline.com'
docs_dir: 'assessments'

theme:
  name: material
  theme_dir: 'custom_theme'
  include_sidebar: false
  palette:
    primary: 'teal'
    accent: 'deep orange'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/cpfUVj'

# Enable custom.css
extra_css:
  - 'assets/css/custom.css'

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - admonition
  - codehilite:
      guess_lang: false
